# Generated by Django 5.2.6 on 2025-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_for_dispatch',
            field=models.BooleanField(default=True),
        ),
    ]
