# Generated by Django 5.2.6 on 2025-09-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('total_beds', models.IntegerField(default=0)),
                ('available_beds', models.IntegerField(default=0)),
                ('emergency_capacity', models.CharField(choices=[('LOW', 'Low Load'), ('MODERATE', 'Moderate Load'), ('HIGH', 'High Load'), ('FULL', 'At Capacity')], default='MODERATE', max_length=20)),
                ('specialties', models.TextField(blank=True, help_text='Comma-separated list of medical specialties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('BASIC', 'Basic Life Support'), ('ADVANCED', 'Advanced Life Support'), ('CRITICAL', 'Critical Care')], default='BASIC', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('TRANSPORTING', 'Transporting'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('equipment_list', models.TextField(blank=True, help_text='List of equipment available in this unit')),
                ('max_patients', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_paramedic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ambulance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ambulance',
                'verbose_name_plural': 'Ambulances',
                'ordering': ['unit_number'],
            },
        ),
    ]
