# Generated by Django 5.2.6 on 2025-09-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='current_emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_assignment', to='emergencies.emergencycall'),
        ),
    ]
