# Generated by Django 5.2.6 on 2025-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
