# Generated by Django 5.2.6 on 2025-09-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('caller_name', models.CharField(blank=True, max_length=100)),
                ('caller_phone', models.CharField(max_length=15)),
                ('emergency_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('TRAUMA', 'Trauma'), ('CARDIAC', 'Cardiac Arrest'), ('STROKE', 'Stroke'), ('RESPIRATORY', 'Respiratory Distress'), ('FIRE', 'Fire Emergency'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DISPATCHED', 'Dispatched'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('TRANSPORTING', 'Transporting'), ('AT_HOSPITAL', 'At Hospital'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('on_scene_at', models.DateTimeField(blank=True, null=True)),
                ('transporting_at', models.DateTimeField(blank=True, null=True)),
                ('at_hospital_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_condition', models.TextField(blank=True)),
                ('hospital_destination', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.ambulance')),
                ('assigned_paramedic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calls', to=settings.AUTH_USER_MODEL)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Call',
                'verbose_name_plural': 'Emergency Calls',
                'ordering': ['-received_at'],
            },
        ),
    ]
