# Generated by Django 5.2.6 on 2025-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_emergencycall_emergency_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='caller_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='description',
            field=models.TextField(),
        ),
    ]
