# Generated by Django 5.2.6 on 2025-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_alter_emergencycall_caller_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycall',
            name='emergency_images',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries containing image metadata: {url: 'path/to/image.jpg', timestamp: 'ISO datetime'}"),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycall',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
